import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Camp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <h2>Header</h2>
      </header>
      <section id="main">
        <h1>Guest Book</h1>
        <h2>TEst</h2>
      </section>

      <footer>
        <h2>Footer</h2>
      </footer>
    </div>
  );
}
